export { default as Header } from './Header';
export { default as Nav } from './Nav';
export { default as Footer } from './Footer';
export { default as Home } from './Home';
export { default as About } from './About';
export { default as NewPost } from './NewPost';
export { default as PostPage } from './PostPage';
export { default as Missing } from './Missing';
export { default as EditPost } from './EditPost'